# Generated by Django 4.0.6 on 2022-09-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAgent', '0002_agent_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_address',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent_address',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
