# Generated by Django 4.0.6 on 2022-09-06 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppAgent', '0003_alter_agent_address_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KYC_Name', models.CharField(max_length=50)),
                ('frontside_image', models.ImageField(upload_to='KYC')),
                ('backside_image', models.ImageField(blank=True, null=True, upload_to='KYC')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'user_type': 'Agent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AgentKYCUserIDs', related_query_name='AgentKYCUserID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent_Bank_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('IFSC_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('cancel_cheque', models.ImageField(upload_to='Cancel_cheque')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'user_type': 'Agent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AgentBankUserIDs', related_query_name='AgentBankUserID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
