# Generated by Django 4.0.6 on 2022-09-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAgent', '0004_agent_kyc_agent_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_bank_details',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent_kyc',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
