# Generated by Django 4.0.6 on 2022-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAgent', '0005_agent_bank_details_is_verify_agent_kyc_is_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Verify_Email_Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_verify_email', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=7)),
                ('gen_datetime', models.DateTimeField(auto_now_add=True)),
                ('exp_datetime', models.DateTimeField()),
                ('is_verify', models.BooleanField(default=False)),
                ('country_code', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('is_verify_phone', models.BooleanField(default=False)),
            ],
        ),
    ]
