# Generated by Django 4.0.6 on 2022-09-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAgent', '0007_alter_agent_verify_email_mobile_exp_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='agent_address',
            name='longitude',
        ),
    ]
