# Generated by Django 4.0.6 on 2022-09-14 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppAgent', '0008_remove_agent_address_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_bank_details',
            name='user_id',
            field=models.ForeignKey(default=99, limit_choices_to={'is_active': True, 'user_type': 'Agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='AgentBankUserIDs', related_query_name='AgentBankUserID', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
