# Generated by Django 4.0.6 on 2022-09-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAgent', '0009_alter_agent_bank_details_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_kyc',
            name='UserKYCImage',
            field=models.ImageField(default='aaa.jpg', upload_to='KYC'),
            preserve_default=False,
        ),
    ]
