# Generated by Django 4.0.6 on 2022-09-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAgent', '0013_rename_user_idkyc_agent_kyc_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent_kyc',
            old_name='user_id',
            new_name='user_idKYC',
        ),
    ]
