# Generated by Django 4.0.6 on 2022-08-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLog',
        ),
    ]
