# Generated by Django 4.0.6 on 2022-08-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0003_user_is_verified_user_user_tnc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_verify',
        ),
    ]
