# Generated by Django 4.0.6 on 2022-08-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0004_rename_is_verified_user_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode_db',
            name='Area_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pincode_db',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pincode_db',
            name='Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pincode_db',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
