# Generated by Django 4.0.6 on 2022-09-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0008_user_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemanddevicelog',
            old_name='user_id',
            new_name='user_idSysLog',
        ),
    ]
