# Generated by Django 4.0.6 on 2022-09-21 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0009_rename_user_id_systemanddevicelog_user_idsyslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemanddevicelog',
            name='user_idSysLog',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='SDLUserID', to=settings.AUTH_USER_MODEL),
        ),
    ]
