# Generated by Django 4.0.6 on 2022-09-21 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0010_alter_systemanddevicelog_user_idsyslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLB_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_answer', models.IntegerField(choices=[(0, 'None'), (1, 'Poor'), (2, 'Average'), (3, 'Fair'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Review_by', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'user_type': 'EndUser'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='ReviewUserID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
