# Generated by Django 4.0.6 on 2022-09-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0011_clb_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clb_review',
            name='review_answer',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
