# Generated by Django 4.0.6 on 2022-09-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0013_couriercompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriercompany',
            name='GST_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='couriercompany',
            name='PanCard_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='couriercompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='couriercompany',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
