# Generated by Django 4.0.6 on 2022-09-23 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0014_alter_couriercompany_gst_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier_Company_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_answer', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('CC_id', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ReviewCCIds', related_query_name='ReviewCCId', to='AppAdmin.couriercompany')),
                ('Review_User', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'user_type': 'EndUser'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='ReviewByUserID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
