# Generated by Django 4.0.6 on 2022-09-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0016_pincode_db_cc_pin_id_pincode_db_is_clb_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pincode_db',
            name='is_pickup',
        ),
    ]
