# Generated by Django 4.0.6 on 2022-09-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0017_remove_pincode_db_is_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceForCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceType', models.CharField(choices=[('Standard', 'Standard'), ('Priority', 'Priority')], default='Standard', max_length=50)),
                ('ShipmentType', models.CharField(choices=[('Documents', 'Documents'), ('Parcel', 'Parcel')], default='Documents', max_length=50)),
                ('TravelBy', models.CharField(choices=[('Air', 'Air'), ('Surface', 'Surface')], default='Surface', max_length=50)),
                ('Weight_From', models.IntegerField()),
                ('Weight_To', models.IntegerField()),
                ('Local', models.IntegerField()),
                ('State', models.IntegerField()),
                ('RestOfInida', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('CC_Price_id', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='PriceCCIds', related_query_name='PriceCCId', to='AppAdmin.couriercompany')),
            ],
        ),
        migrations.CreateModel(
            name='Our_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceType', models.CharField(choices=[('Standard', 'Standard'), ('Priority', 'Priority')], default='Standard', max_length=50)),
                ('ShipmentType', models.CharField(choices=[('Documents', 'Documents'), ('Parcel', 'Parcel')], default='Documents', max_length=50)),
                ('TravelBy', models.CharField(choices=[('Air', 'Air'), ('Surface', 'Surface')], default='Surface', max_length=50)),
                ('Weight_From', models.IntegerField()),
                ('Weight_To', models.IntegerField()),
                ('Local', models.IntegerField()),
                ('State', models.IntegerField()),
                ('RestOfInida', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('CC_OurPrice_id', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='OurPriceCCIds', related_query_name='OurPriceCCId', to='AppAdmin.couriercompany')),
            ],
        ),
    ]
