# Generated by Django 4.0.6 on 2022-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0018_priceforcustomer_our_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriercompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='CourierLogo'),
        ),
    ]
