# Generated by Django 4.0.6 on 2022-09-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0019_couriercompany_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceforcustomer',
            old_name='RestOfInida',
            new_name='RestOfIndia',
        ),
    ]
