# Generated by Django 4.0.6 on 2022-09-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0022_alter_priceforcustomer_travelby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_price',
            old_name='RestOfInida',
            new_name='RestOfIndia',
        ),
    ]
