# Generated by Django 4.0.6 on 2022-09-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0023_rename_restofinida_our_price_restofindia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingslot',
            name='allow_time_after_start_time',
            field=models.TimeField(default='00:30:00'),
            preserve_default=False,
        ),
    ]
