# Generated by Django 4.0.6 on 2022-10-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0026_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='solve_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='solve_timeshtamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
