# Generated by Django 4.0.6 on 2022-10-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0028_issue_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('country_code', models.CharField(max_length=10)),
                ('requester_phone', models.CharField(max_length=20)),
                ('requester_email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('order_id', models.CharField(max_length=20)),
                ('is_solve', models.BooleanField(default=False)),
                ('solve_details', models.TextField(blank=True, max_length=500, null=True)),
                ('solved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('solve_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved')], default='Pending', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Support_User_Id', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='SupportUserIds', related_query_name='SupportUserId', to=settings.AUTH_USER_MODEL)),
                ('issue_Cate_id', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='IssueCateIds', related_query_name='IssueCateId', to='AppAdmin.issue_category')),
            ],
        ),
    ]
