# Generated by Django 4.0.6 on 2022-10-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0029_support_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In_Progress', 'In_Progress'), ('Closed', 'Closed'), ('Reopen', 'Reopen')], default='Open', max_length=50),
        ),
    ]
