# Generated by Django 4.0.6 on 2022-10-03 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0030_alter_support_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support_ticket',
            old_name='solved_by',
            new_name='closed_by',
        ),
        migrations.RenameField(
            model_name='support_ticket',
            old_name='solve_details',
            new_name='closing_details',
        ),
        migrations.RenameField(
            model_name='support_ticket',
            old_name='solve_timestamp',
            new_name='closing_timestamp',
        ),
        migrations.RenameField(
            model_name='support_ticket',
            old_name='is_solve',
            new_name='is_closed',
        ),
        migrations.RenameField(
            model_name='support_ticket',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='support_ticket',
            name='Support_User_Id',
        ),
        migrations.AddField(
            model_name='support_ticket',
            name='client_User_Id',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ClientUserIds', related_query_name='ClientUserId', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
