# Generated by Django 4.0.6 on 2022-10-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0031_rename_solved_by_support_ticket_closed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_ticket',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='support_ticket',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='support_ticket',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='support_ticket',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='support_ticket',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='support_ticket',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='support_ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
