# Generated by Django 4.0.6 on 2022-10-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0032_alter_support_ticket_country_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue_category',
            old_name='name',
            new_name='Issue_cat_name',
        ),
    ]
