# Generated by Django 4.0.6 on 2022-10-03 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0033_rename_name_issue_category_issue_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_ticket',
            name='client_User_Id',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClientUserIds', related_query_name='ClientUserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='support_ticket',
            name='issue_Cate_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IssueCateIds', related_query_name='IssueCateId', to='AppAdmin.issue_category'),
        ),
    ]
