# Generated by Django 4.0.6 on 2022-10-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0034_alter_support_ticket_client_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support_Ticket',
        ),
    ]
