# Generated by Django 4.0.6 on 2022-10-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0036_support_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_ticket',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
