# Generated by Django 4.0.6 on 2022-10-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0037_alter_support_ticket_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue_category',
            old_name='Issue_cat_name',
            new_name='Catename',
        ),
    ]
