# Generated by Django 4.0.6 on 2022-10-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0041_rename_image_notification_notif_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_description', models.TextField(blank=True, max_length=500, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='Banner')),
                ('banner_start', models.DateTimeField(blank=True, null=True)),
                ('banner_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_description', models.TextField(blank=True, max_length=500, null=True)),
                ('offer_amount', models.IntegerField(blank=True, null=True)),
                ('offer_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('offer_start', models.DateTimeField(blank=True, null=True)),
                ('offer_end', models.DateTimeField(blank=True, null=True)),
                ('offer_minium_value', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, max_length=251, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
