# Generated by Django 4.0.6 on 2022-10-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0043_rename_banner_description_banner_banner_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_discount',
            name='offer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
