# Generated by Django 4.0.6 on 2022-10-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0044_offer_discount_offer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_discount',
            name='offer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
