# Generated by Django 4.0.6 on 2022-10-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0046_alter_offer_discount_offer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemanddevicelog',
            name='active_fcm',
            field=models.BooleanField(default=True),
        ),
    ]
