# Generated by Django 4.0.6 on 2022-10-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0048_service_type_shipment_type_travel_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Type',
        ),
        migrations.DeleteModel(
            name='Shipment_Type',
        ),
    ]
