# Generated by Django 4.0.6 on 2022-10-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0049_delete_service_type_delete_shipment_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel_Type',
        ),
    ]
