# Generated by Django 4.0.6 on 2022-08-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEndUser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndUser_Address',
        ),
    ]
