# Generated by Django 4.0.6 on 2022-09-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEndUser', '0007_alter_sender_receiver_address_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sender_receiver_address',
            old_name='user_id',
            new_name='user_idSRAdd',
        ),
    ]
