# Generated by Django 4.0.6 on 2022-10-14 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppEndUser', '0009_remove_sender_receiver_address_address_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Card_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_name', models.CharField(blank=True, max_length=112, null=True)),
                ('card_number', models.CharField(blank=True, max_length=112, null=True)),
                ('exp_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('UserCard_id', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'user_type': 'EndUser'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CardEndUserIDs', related_query_name='CardEndUserID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
