# Generated by Django 4.0.6 on 2022-10-17 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0050_delete_travel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppEndUser', '0011_alter_user_card_details_exp_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='End_User_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('booking_order_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('ServiceType', models.CharField(choices=[('Standard', 'Standard'), ('Priority', 'Priority')], default='Standard', max_length=50)),
                ('ShipmentType', models.CharField(choices=[('Documents', 'Documents'), ('Parcel', 'Parcel')], default='Documents', max_length=50)),
                ('TravelBy', models.CharField(choices=[('Air', 'Air'), ('Surface', 'Surface'), ('Air/Surface', 'Air/Surface')], default='Air/Surface', max_length=50)),
                ('content_of_shipment', models.CharField(blank=True, max_length=200, null=True)),
                ('value_of_goods', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('dimension', models.CharField(blank=True, max_length=100, null=True)),
                ('volumetric_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('texable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.IntegerField(blank=True, null=True)),
                ('cgst', models.IntegerField(blank=True, null=True)),
                ('totalcharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_tnc', models.BooleanField(default=True)),
                ('eway_bill_no', models.CharField(blank=True, max_length=200, null=True)),
                ('eway_bill_date', models.DateField(blank=True, null=True)),
                ('endUser_gstNo', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Receiver_id', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EURecevierIDs', related_query_name='EURecevierID', to='AppEndUser.sender_receiver_address')),
                ('Sender_id', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EUSenderIDs', related_query_name='EUSenderID', to='AppEndUser.sender_receiver_address')),
                ('company_name', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EUCourierCompanyIDs', related_query_name='EUCourierCompanyID', to='AppAdmin.couriercompany')),
                ('user_idEndOrder', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'user_type': 'EndUser'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EUorderUserIDs', related_query_name='EUorderUserID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
