# Generated by Django 4.0.6 on 2022-10-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEndUser', '0012_end_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='end_user_order',
            name='awb_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
