# Generated by Django 4.0.6 on 2022-10-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEndUser', '0014_rename_company_name_end_user_order_company_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='end_user_order',
            name='pickup_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
