# Generated by Django 4.0.6 on 2022-10-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEndUser', '0015_end_user_order_pickup_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_user_order',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='end_user_order',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='end_user_order',
            name='volumetric_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='end_user_order',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
